const products = [
  {
    pname: "Smartphone X",
    pprice: 49.99,
    pimages: "https://picsum.photos/200/200?random=1",
    pcategory: "Electronics",
    psubcategory: "Gadgets",
    ptitle: "Smart Device",
    pdescription:
      "A revolutionary smart device that will make your life easier.",
    porigin: "USA",
  },
  {
    pname: "Stylish T-Shirt",
    pprice: 29.99,
    pimages: "https://picsum.photos/200/200?random=2",
    pcategory: "Clothing",
    psubcategory: "Casual Wear",
    ptitle: "Fashionable T-Shirt",
    pdescription: "A comfortable and stylish T-shirt for everyday wear.",
    porigin: "Italy",
  },
  {
    pname: "Premium Cookware Set",
    pprice: 79.99,
    pimages: "https://picsum.photos/200/200?random=3",
    pcategory: "Home and Kitchen",
    psubcategory: "Cookware",
    ptitle: "Premium Cookware Set",
    pdescription: "Upgrade your kitchen with this high-quality cookware set.",
    porigin: "Germany",
  },
  {
    pname: "Wireless Earbuds",
    pprice: 69.99,
    pimages: "https://picsum.photos/200/200?random=4",
    pcategory: "Electronics",
    psubcategory: "Audio",
    ptitle: "High-Quality Wireless Earbuds",
    pdescription:
      "Immerse yourself in your favorite music with these wireless earbuds.",
    porigin: "Japan",
  },
  {
    pname: "Casual Sneakers",
    pprice: 39.99,
    pimages: "https://picsum.photos/200/200?random=5",
    pcategory: "Footwear",
    psubcategory: "Sneakers",
    ptitle: "Comfortable Casual Sneakers",
    pdescription: "Walk in style and comfort with these casual sneakers.",
    porigin: "Brazil",
  },
  {
    pname: "Non-Stick Pan",
    pprice: 34.99,
    pimages: "https://picsum.photos/200/200?random=6",
    pcategory: "Home and Kitchen",
    psubcategory: "Cookware",
    ptitle: "Durable Non-Stick Pan",
    pdescription: "Cook delicious meals effortlessly with this non-stick pan.",
    porigin: "France",
  },
  {
    pname: "Gaming Mouse",
    pprice: 59.99,
    pimages: "https://picsum.photos/200/200?random=7",
    pcategory: "Electronics",
    psubcategory: "Gaming Accessories",
    ptitle: "High-Performance Gaming Mouse",
    pdescription: "Gain a competitive edge with this advanced gaming mouse.",
    porigin: "South Korea",
  },
  {
    pname: "Leather Wallet",
    pprice: 49.99,
    pimages: "https://picsum.photos/200/200?random=8",
    pcategory: "Fashion",
    psubcategory: "Accessories",
    ptitle: "Classic Leather Wallet",
    pdescription:
      "Store your essentials in style with this classic leather wallet.",
    porigin: "Italy",
  },
  {
    pname: "Fitness Tracker",
    pprice: 79.99,
    pimages: "https://picsum.photos/200/200?random=9",
    pcategory: "Fitness",
    psubcategory: "Wearables",
    ptitle: "Smart Fitness Tracker",
    pdescription:
      "Track your fitness goals with this intelligent fitness tracker.",
    porigin: "USA",
  },
  {
    pname: "Outdoor Camping Tent",
    pprice: 129.99,
    pimages: "https://picsum.photos/200/200?random=10",
    pcategory: "Outdoor",
    psubcategory: "Camping Gear",
    ptitle: "Durable Camping Tent",
    pdescription:
      "Experience the great outdoors with this sturdy camping tent.",
    porigin: "Canada",
  },
  {
    pname: "Professional Camera",
    pprice: 899.99,
    pimages: "https://picsum.photos/200/200?random=11",
    pcategory: "Electronics",
    psubcategory: "Photography",
    ptitle: "High-End Professional Camera",
    pdescription: "Capture stunning moments with this top-of-the-line camera.",
    porigin: "Japan",
  },
  {
    pname: "Cozy Blanket",
    pprice: 44.99,
    pimages: "https://picsum.photos/200/200?random=12",
    pcategory: "Home and Living",
    psubcategory: "Bedding",
    ptitle: "Soft and Cozy Blanket",
    pdescription: "Stay warm and comfortable with this soft and cozy blanket.",
    porigin: "Netherlands",
  },
  {
    pname: "Stainless Steel Water Bottle",
    pprice: 24.99,
    pimages: "https://picsum.photos/200/200?random=13",
    pcategory: "Sports and Outdoors",
    psubcategory: "Hydration",
    ptitle: "Durable Stainless Steel Water Bottle",
    pdescription:
      "Stay hydrated on the go with this durable stainless steel water bottle.",
    porigin: "China",
  },
  {
    pname: "Business Laptop Bag",
    pprice: 59.99,
    pimages: "https://picsum.photos/200/200?random=14",
    pcategory: "Fashion",
    psubcategory: "Bags",
    ptitle: "Professional Laptop Bag",
    pdescription:
      "Carry your laptop in style with this professional laptop bag.",
    porigin: "Germany",
  },
  {
    pname: "Wireless Charging Pad",
    pprice: 39.99,
    pimages: "https://picsum.photos/200/200?random=15",
    pcategory: "Electronics",
    psubcategory: "Accessories",
    ptitle: "Convenient Wireless Charging Pad",
    pdescription:
      "Charge your devices effortlessly with this wireless charging pad.",
    porigin: "South Korea",
  },
  {
    pname: "Rustic Coffee Table",
    pprice: 149.99,
    pimages: "https://picsum.photos/200/200?random=16",
    pcategory: "Furniture",
    psubcategory: "Living Room",
    ptitle: "Rustic Wooden Coffee Table",
    pdescription:
      "Add a touch of rustic charm to your living room with this coffee table.",
    porigin: "Canada",
  },
  {
    pname: "Bluetooth Speaker",
    pprice: 79.99,
    pimages: "https://picsum.photos/200/200?random=17",
    pcategory: "Electronics",
    psubcategory: "Audio",
    ptitle: "Portable Bluetooth Speaker",
    pdescription:
      "Enjoy your favorite music anywhere with this portable Bluetooth speaker.",
    porigin: "USA",
  },
  {
    pname: "Comfortable Office Chair",
    pprice: 129.99,
    pimages: "https://picsum.photos/200/200?random=18",
    pcategory: "Furniture",
    psubcategory: "Office",
    ptitle: "Ergonomic Office Chair",
    pdescription:
      "Stay comfortable during work hours with this ergonomic office chair.",
    porigin: "China",
  },
  {
    pname: "Designer Sunglasses",
    pprice: 59.99,
    pimages: "https://picsum.photos/200/200?random=19",
    pcategory: "Fashion",
    psubcategory: "Accessories",
    ptitle: "Stylish Designer Sunglasses",
    pdescription: "Protect your eyes in style with these designer sunglasses.",
    porigin: "Italy",
  },
  {
    pname: "Portable Power Bank",
    pprice: 29.99,
    pimages: "https://picsum.photos/200/200?random=20",
    pcategory: "Electronics",
    psubcategory: "Accessories",
    ptitle: "Compact Portable Power Bank",
    pdescription:
      "Charge your devices on the go with this compact portable power bank.",
    porigin: "Japan",
  },
];


export {products}